<?xml version="1.0" encoding="utf-8"?><Database Name="InventoryDB" Class="CategoryDataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=(LocalDB)\MSSQLLocalDB;AttachDbFilename=|DataDirectory|\InventoryDB.mdf;Integrated Security=True" SettingsObjectName="EasyInventory.Properties.Settings" SettingsPropertyName="InventoryDBConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.tblCategory" Member="tblCategories">
    <Type Name="tblCategory">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="categoryName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="description" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>